site_name: "Homelab"
repo_url: "https://github.com/bgaillard/homelab"
nav:
  - Introduction: index.md
  - Kubernetes: kubernetes.md
  - Incus: incus.md
  - Pi-hole: pi-hole.md
  - Restic: restic.md
  - Vault: vault.md
  - Wireguard: wireguard.md
  - IaC Updater: iac-updater.md

# @see https://squidfunk.github.io/mkdocs-material/
theme: 
  #name: readthedocs
  name: material
  features:
    - content.code.copy
    - content.code.select
    - header.autohide
  palette:
    scheme: slate

markdown_extensions:
  # @see https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - "docs/index.md"
