---
# Server store their backups into the /src/backups/ directory which mounts a Samba share.
#
# The Samba share is then backed up to an off-site location using Restic.
backups_smb_server: "0.0.0.0"
backups_smb_share: "SambaShare"
backups_smb_username: "SambaUser"
backups_smb_password: "SambaPassword"
backups_smb_version: "SambaVersion"

# GIT configuration
git_user_email: "john.doe@email.com"
git_user_name: "John Doe"

# GitHub configuration
github_pat: "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
github_username: "john_doe"

# IaC Updater
iac_updater_client_id: "xxxxxxxx"
iac_updater_installation_id: "xxxxxxxx"
iac_updater_private_key: "xxxxxxxx"

# Pi-hole application password used to manage update of Pi-hole IaC
pi_hole_app_password: "xxxxxxxx"

# Infomaniak Swiss Backup configuration
swiss_backup_location: "location"
swiss_backup_region: "region"
swiss_backup_project_name: "project_name"
swiss_backup_password: "password"
swiss_backup_user_name: "username"

# Restic configuration
restic_password: "restic_password"
