---
- name: Install 'core' Linux packages
  become: true
  ansible.builtin.package:
    name:
      # If a tool is supported by mise, prefer installing it using mise because it allows to always use the latest
      # version.
      - restic
      - sysstat
    state: latest
