---
# Servers do no need several Linux services running by default.
#
# Please note that not useful network services are disabled through the '04-network.yml' file.
disabled_services:
  - bluetooth
  - cups

# Network configuration
network:

  # Allows to find the Ethernet network interface by its MAC address and declare it with the 'eth0' name.
  mac_address: "00:00:00:00:00:00"

  # DHCP is enabled by default
  dhcp: true

  # Only used if 'dhcp' is set to false
  static:
    ip_address: 0.0.0.0
    netmask: 255.255.255.0
    gateway: 192.168.1.1
    dns_1: 8.8.8.8
    dns_2: 8.8.4.4
