---
# Servers do no need several Linux services running by default.
#
# Please note that not useful network services are disabled through the '04-network.yml' file.
disabled_services:
  - bluetooth
  - cups

# Network configuration
network:
  nameservers:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4

  ethernet:

    # Enable or disable the Ethernet network interface configuration
    enabled: true

    # Allows to find the Ethernet network interface by its MAC address and declare it with the 'eth0' name.
    mac_address: "00:00:00:00:00:00"

    # DHCP is enabled by default
    dhcp: true

    # Only used if 'dhcp' is set to false
    static:
      ip_address: 0.0.0.0
      netmask: 255.255.255.0
      gateway: 192.168.1.1

  wifi:

    # Enable or disable the WiFi network interface configuration
    enabled: false

    # Allows to find the WiFi network interface by its MAC address and declare it with the 'wlan0' name.
    mac_address: "00:00:00:00:00:00"

    # DHCP is enabled by default
    dhcp: true

    # Only used if 'dhcp' is set to false
    static:
      ip_address: 0.0.0.0
      netmask: 255.255.255.0
      gateway: 192.168.1.1

    wpa_ssid: ""
    wpa_psk: ""

# Additional Linux packages to be installed
packages: []
