---
- name: POST /dns/blocking
  ansible.builtin.uri:
    url: http://pi-3/api/dns/blocking?sid={{ auth.json.session.sid }}
    method: POST
    body_format: json
    body: "{{ api.dns_control.post }}"
  when: api is defined and api.dns_control is defined and api.dns_control.post is defined
