---
- name: PATCH /config
  ansible.builtin.uri:
    url: http://pi-3/api/config?restart=true&sid={{ auth.json.session.sid }}
    method: PATCH
    body_format: json
    body: "{{ item }}"
  loop: "{{ api.pi_hole_configuration.patch }}"
  when: api is defined and api.pi_hole_configuration is defined and api.pi_hole_configuration.patch is defined
