---
# The bellow variables have names equal to the "sections" of the Pi-hole API documentation page.
#
# For example the section named "Domain Management" is managed through the variable "domain_management" (i.e. we
# convert the camel case section title to snake case).
#
# The variables MUST be defined in the same order as the sections appear in the documentation page.
#
# @see https://pi.hole/api/docs


# Authentication
authentication:
  post:
    password: "xxxxxxxx"


# DNS control
dns_control:
  post: 
    blocking: true
    timer: null


# Group Management
# TODO: Implement Group Management


# Client Management
# TODO: Implement Client Management


# List Management
list_management:
  put: []


# Domain Management
domain_management: 
  put: []


# FTL information
# TODO: Implement FTL information


# Network information
# TODO: Implement Network information


# Pi-hole Configuration
pi_hole_configuration:
  patch: []


# DHCP
# TODO: Implement DHCP
