---
- name: Create the '/root/.local/bin' directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "/root/.local/bin"
    state: directory
    mode: '0700'

- name: Copy file '/root/.local/bin/backup-vault'
  become: true
  ansible.builtin.copy:
    src: root/.local/bin/backup-vault
    dest: "/root/.local/bin/backup-vault"
    mode: u=rx
    force: true

- name: Create the '/var/log/backup-vault/' directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "/var/log/backup-vault/"
    state: directory
    owner: "{{ ansible_facts['env']['USER'] }}"
    group: "{{ ansible_facts['env']['USER'] }}"
    mode: '0700'

- name: Configure vault backup cron job
  become: true
  ansible.builtin.cron:
    name: "Backup the Vault data"
    job: "/root/.local/bin/backup-vault >> /var/log/backup-vault/backup-vault.log 2>&1"
    state: present
    user: root
    minute: "0"
    hour: "0"
    weekday: "*"
    month: "*"
    day: "*"
