---
all:
  hosts:
    inspiron-3847:
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
    pi-3:
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
