---
- hosts: inspiron-3847
  roles:
    - role: common
      vars:
        network:
          ethernet:
            mac_address: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/servers/inspiron-3847:mac_address') }}"
        packages:
          - curl
    - incus
    - inspiron-3847
