pi_hole_lists:
- address: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  comment: StevenBlack
  enabled: true
  groups:
  - 0
  id: 1
  type: block
- address: https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/ultimate.txt
  comment: hagezi - Multi ULTIMATE
  enabled: true
  groups:
  - 0
  id: 2
  type: block
