pi_hole_domains:
- comment: Added from Query Log
  domain: dsp.360yield.com
  enabled: true
  groups:
  - 0
  id: 1
  kind: exact
  type: deny
- comment: Adagio
  domain: ^.*[\.]?4dex\.io$
  enabled: true
  groups:
  - 0
  id: 2
  kind: regex
  type: deny
- comment: Google Ad Traffic Quality
  domain: ^.*[\.]?adtrafficquality\.google$
  enabled: true
  groups:
  - 0
  id: 3
  kind: regex
  type: deny
- comment: Bliink
  domain: ^.*[\.]?bliink\.io$
  enabled: true
  groups:
  - 0
  id: 4
  kind: regex
  type: deny
- comment: Criteo
  domain: ^.*[\.]?criteo\.net$
  enabled: true
  groups:
  - 0
  id: 5
  kind: regex
  type: deny
- comment: null
  domain: ^.*[\.]?fastcmp\.com$
  enabled: true
  groups:
  - 0
  id: 6
  kind: regex
  type: deny
- comment: Mediago
  domain: ^.*[\.]?mediago\.io$
  enabled: true
  groups:
  - 0
  id: 7
  kind: regex
  type: deny
- comment: null
  domain: ^.*[\.]?newsroom\.bi$
  enabled: true
  groups:
  - 0
  id: 8
  kind: regex
  type: deny
- comment: OpenWeb
  domain: ^.*[\.]?omnitagjs\.com$
  enabled: true
  groups:
  - 0
  id: 9
  kind: regex
  type: deny
- comment: Outbrain
  domain: ^.*[\.]?outbrain\.com$
  enabled: true
  groups:
  - 0
  id: 10
  kind: regex
  type: deny
- comment: Adverstisement platform
  domain: ^.*[\.]?richaudience\.com$
  enabled: true
  groups:
  - 0
  id: 11
  kind: regex
  type: deny
- comment: Equativ (formerly Smart AdServer)
  domain: ^.*[\.]?smartadserver\.com$
  enabled: true
  groups:
  - 0
  id: 12
  kind: regex
  type: deny
- comment: Sparteo
  domain: ^.*[\.]?sparteo\.com$
  enabled: true
  groups:
  - 0
  id: 13
  kind: regex
  type: deny
- comment: Added from Query Log
  domain: prebid.a-mo.net
  enabled: true
  groups:
  - 0
  id: 14
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: data00.adlooxtracking.com
  enabled: true
  groups:
  - 0
  id: 15
  kind: exact
  type: deny
- comment: null
  domain: redirect.affilizz.com
  enabled: true
  groups:
  - 0
  id: 16
  kind: exact
  type: allow
- comment: Added from Query Log
  domain: events.agrvt.com
  enabled: true
  groups:
  - 0
  id: 17
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: a.amxrtb.com
  enabled: true
  groups:
  - 0
  id: 18
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: audienceexposure.com
  enabled: true
  groups:
  - 0
  id: 19
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: ghent-gce-nl.bidswitch.net
  enabled: true
  groups:
  - 0
  id: 20
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: altice.endpoint.bidwatch.io
  enabled: true
  groups:
  - 0
  id: 21
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: ads21.console.adtarget.com.tr
  enabled: true
  groups:
  - 0
  id: 22
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: api.consentframework.com
  enabled: true
  groups:
  - 0
  id: 23
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: csync.copper6.com
  enabled: true
  groups:
  - 0
  id: 24
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: casale-match.dotomi.com
  enabled: true
  groups:
  - 0
  id: 25
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: publishers.edisound.com
  enabled: true
  groups:
  - 0
  id: 26
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: d7.eu-3-id5-sync.com
  enabled: true
  groups:
  - 0
  id: 27
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: d5.eu-4-id5-sync.com
  enabled: true
  groups:
  - 0
  id: 28
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: www.flashb.id
  enabled: true
  groups:
  - 0
  id: 29
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: user-sync.fwmrm.net
  enabled: true
  groups:
  - 0
  id: 30
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: 7dcde.v.fwmrm.net
  enabled: true
  groups:
  - 0
  id: 31
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: 83a19.v.fwmrm.net
  enabled: true
  groups:
  - 0
  id: 32
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: e2c65.gcp.gvt2.com
  enabled: true
  groups:
  - 0
  id: 33
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: events.mediarithmics.com
  enabled: true
  groups:
  - 0
  id: 34
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: cs.minutemedia-prebid.com
  enabled: true
  groups:
  - 0
  id: 35
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: logs.netflix.com
  enabled: true
  groups:
  - 0
  id: 36
  kind: exact
  type: allow
- comment: Added from Query Log
  domain: pbs.optidigital.com
  enabled: true
  groups:
  - 0
  id: 37
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: plausible.io
  enabled: true
  groups:
  - 0
  id: 38
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: api.poool.fr
  enabled: true
  groups:
  - 0
  id: 39
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: csync.smilewanted.com
  enabled: true
  groups:
  - 0
  id: 40
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: www.viously.com
  enabled: true
  groups:
  - 0
  id: 41
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: measurements-api.wonderpush.com
  enabled: true
  groups:
  - 0
  id: 42
  kind: exact
  type: deny
- comment: Added from Query Log
  domain: x.com
  enabled: true
  groups:
  - 0
  id: 43
  kind: exact
  type: deny
